/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lockedme;

import org.junit.jupiter.api.Test;

import lockedme.businesslogic.FileOperations;

class AppTest {
    @Test void sortFileNames() {
        FileOperations fileOperations = new FileOperations();
        fileOperations.sortFileNames();
        fileOperations.addFile();
        fileOperations.deleteFile();
        fileOperations.searchFile();
    }
}
